# Generated by Django 3.0.4 on 2020-03-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_auto_20200310_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Linguagens',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
